/** Sanitized post-August-13 trial recordings, captured August 17–September 7, 2026.
 * Only boss sheets, relative cooldowns, personal success rates and shared pools are retained.
 * Server and engine store resolved attack/cast speed under different field names.
 * Curve parameters are inferred from the recorded bend between the 4- and 8-point slopes.
 * No participant names, character IDs, guild names or account data are included.
 */
export const RECORDED_TRIAL_BOSSES = [
    {
        recordedOn: '2026-08-18',
        tier: 7,
        participants: 8,
        hrid: '/monsters/trial_badger',
        combatDetails: {
            maxHitpoints: 633420,
            maxManapoints: 586500,
            attackInterval: 2155172412,
            totalCastSpeed: 0.24,
            stabAccuracyRating: 170,
            slashAccuracyRating: 714,
            smashAccuracyRating: 170,
            rangedAccuracyRating: 170,
            magicAccuracyRating: 170,
            defensiveMaxDamage: 170,
            stabMaxDamage: 170,
            slashMaxDamage: 408,
            smashMaxDamage: 170,
            rangedMaxDamage: 10,
            magicMaxDamage: 10,
            stabEvasionRating: 799,
            slashEvasionRating: 799,
            smashEvasionRating: 799,
            rangedEvasionRating: 1020,
            magicEvasionRating: 578,
            totalArmor: 672,
            totalWaterResistance: 272,
            totalNatureResistance: 272,
            totalFireResistance: 272,
            totalThreat: 100,
            staminaLevel: 160,
            intelligenceLevel: 160,
            attackLevel: 160,
            meleeLevel: 160,
            defenseLevel: 160,
            rangedLevel: 0,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 16,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/fierce_aura',
                level: 64,
                availableAfterSeconds: 51.724,
            },
            {
                abilityHrid: '/abilities/berserk',
                level: 96,
                availableAfterSeconds: 12.931,
            },
            {
                abilityHrid: '/abilities/maim',
                level: 96,
                availableAfterSeconds: 8.621,
            },
            {
                abilityHrid: '/abilities/cleave',
                level: 96,
                availableAfterSeconds: 8.621,
            },
            {
                abilityHrid: '/abilities/scratch',
                level: 96,
                availableAfterSeconds: 6.466,
            },
        ],
    },
    {
        recordedOn: '2026-08-18',
        tier: 7,
        participants: 8,
        hrid: '/monsters/trial_badger',
        combatDetails: {
            maxHitpoints: 633420,
            maxManapoints: 586500,
            attackInterval: 2155172412,
            totalCastSpeed: 0.24,
            stabAccuracyRating: 170,
            slashAccuracyRating: 714,
            smashAccuracyRating: 170,
            rangedAccuracyRating: 170,
            magicAccuracyRating: 170,
            defensiveMaxDamage: 170,
            stabMaxDamage: 170,
            slashMaxDamage: 408,
            smashMaxDamage: 170,
            rangedMaxDamage: 10,
            magicMaxDamage: 10,
            stabEvasionRating: 799,
            slashEvasionRating: 799,
            smashEvasionRating: 799,
            rangedEvasionRating: 1020,
            magicEvasionRating: 578,
            totalArmor: 672,
            totalWaterResistance: 272,
            totalNatureResistance: 272,
            totalFireResistance: 272,
            totalThreat: 100,
            staminaLevel: 160,
            intelligenceLevel: 160,
            attackLevel: 160,
            meleeLevel: 160,
            defenseLevel: 160,
            rangedLevel: 0,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 16,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/fierce_aura',
                level: 64,
                availableAfterSeconds: 51.724,
            },
            {
                abilityHrid: '/abilities/berserk',
                level: 96,
                availableAfterSeconds: 12.931,
            },
            {
                abilityHrid: '/abilities/maim',
                level: 96,
                availableAfterSeconds: 8.621,
            },
            {
                abilityHrid: '/abilities/cleave',
                level: 96,
                availableAfterSeconds: 8.621,
            },
            {
                abilityHrid: '/abilities/scratch',
                level: 96,
                availableAfterSeconds: 6.466,
            },
        ],
    },
    {
        recordedOn: '2026-08-19',
        tier: 1,
        participants: 7,
        hrid: '/monsters/trial_chameleon',
        combatDetails: {
            maxHitpoints: 676775,
            maxManapoints: 632500,
            attackInterval: 2255639097,
            totalCastSpeed: 0.19,
            stabAccuracyRating: 110,
            slashAccuracyRating: 110,
            smashAccuracyRating: 110,
            rangedAccuracyRating: 505.99999999999994,
            magicAccuracyRating: 110,
            defensiveMaxDamage: 110,
            stabMaxDamage: 10,
            slashMaxDamage: 10,
            smashMaxDamage: 10,
            rangedMaxDamage: 385,
            magicMaxDamage: 10,
            stabEvasionRating: 396,
            slashEvasionRating: 396,
            smashEvasionRating: 396,
            rangedEvasionRating: 517,
            magicEvasionRating: 616,
            totalArmor: 245,
            totalWaterResistance: 420,
            totalNatureResistance: 420,
            totalFireResistance: 420,
            totalThreat: 100,
            staminaLevel: 100,
            intelligenceLevel: 100,
            attackLevel: 100,
            meleeLevel: 0,
            defenseLevel: 100,
            rangedLevel: 100,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 14,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/critical_aura',
                level: 40,
                availableAfterSeconds: 52.631,
            },
            {
                abilityHrid: '/abilities/precision',
                level: 60,
                availableAfterSeconds: 13.157,
            },
            {
                abilityHrid: '/abilities/penetrating_shot',
                level: 60,
                availableAfterSeconds: 8.771,
            },
            {
                abilityHrid: '/abilities/rain_of_arrows',
                level: 60,
                availableAfterSeconds: 8.771,
            },
            {
                abilityHrid: '/abilities/steady_shot',
                level: 60,
                availableAfterSeconds: 8.771,
            },
        ],
    },
    {
        recordedOn: '2026-08-21',
        tier: 1,
        participants: 4,
        hrid: '/monsters/trial_hedgehog',
        combatDetails: {
            maxHitpoints: 457600,
            maxManapoints: 440000,
            attackInterval: 2645502644,
            totalCastSpeed: 0.13,
            stabAccuracyRating: 110,
            slashAccuracyRating: 110,
            smashAccuracyRating: 418,
            rangedAccuracyRating: 110,
            magicAccuracyRating: 418,
            defensiveMaxDamage: 286,
            stabMaxDamage: 110,
            slashMaxDamage: 110,
            smashMaxDamage: 286,
            rangedMaxDamage: 10,
            magicMaxDamage: 286,
            stabEvasionRating: 495,
            slashEvasionRating: 495,
            smashEvasionRating: 495,
            rangedEvasionRating: 495,
            magicEvasionRating: 495,
            totalArmor: 270,
            totalWaterResistance: 270,
            totalNatureResistance: 270,
            totalFireResistance: 160,
            totalThreat: 100,
            staminaLevel: 100,
            intelligenceLevel: 100,
            attackLevel: 100,
            meleeLevel: 100,
            defenseLevel: 100,
            rangedLevel: 0,
            magicLevel: 100,
            combatStats: {
                abilityHaste: 8,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/guardian_aura',
                level: 40,
                availableAfterSeconds: 55.556,
            },
            {
                abilityHrid: '/abilities/toughness',
                level: 60,
                availableAfterSeconds: 13.889,
            },
            {
                abilityHrid: '/abilities/spike_shell',
                level: 60,
                availableAfterSeconds: 13.889,
            },
            {
                abilityHrid: '/abilities/natures_veil',
                level: 60,
                availableAfterSeconds: 6.945,
            },
            {
                abilityHrid: '/abilities/fracturing_impact',
                level: 60,
                availableAfterSeconds: 9.259,
            },
        ],
    },
    {
        recordedOn: '2026-08-21',
        tier: 14,
        participants: 47,
        hrid: '/monsters/trial_hedgehog',
        combatDetails: {
            maxHitpoints: 1411200,
            maxManapoints: 960000,
            attackInterval: 1386898432,
            totalCastSpeed: 1.0550000000000002,
            stabAccuracyRating: 240,
            slashAccuracyRating: 240,
            smashAccuracyRating: 912,
            rangedAccuracyRating: 240,
            magicAccuracyRating: 912,
            defensiveMaxDamage: 624,
            stabMaxDamage: 240,
            slashMaxDamage: 240,
            smashMaxDamage: 624,
            rangedMaxDamage: 10,
            magicMaxDamage: 624,
            stabEvasionRating: 1080,
            slashEvasionRating: 1080,
            smashEvasionRating: 1080,
            rangedEvasionRating: 1080,
            magicEvasionRating: 1080,
            totalArmor: 621,
            totalWaterResistance: 621,
            totalNatureResistance: 621,
            totalFireResistance: 368,
            totalThreat: 100,
            staminaLevel: 230,
            intelligenceLevel: 230,
            attackLevel: 230,
            meleeLevel: 230,
            defenseLevel: 230,
            rangedLevel: 0,
            magicLevel: 230,
            combatStats: {
                abilityHaste: 94,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/guardian_aura',
                level: 92,
                availableAfterSeconds: 30.928,
            },
            {
                abilityHrid: '/abilities/toughness',
                level: 138,
                availableAfterSeconds: 7.732,
            },
            {
                abilityHrid: '/abilities/spike_shell',
                level: 138,
                availableAfterSeconds: 7.732,
            },
            {
                abilityHrid: '/abilities/natures_veil',
                level: 138,
                availableAfterSeconds: 3.866,
            },
            {
                abilityHrid: '/abilities/fracturing_impact',
                level: 138,
                availableAfterSeconds: 5.155,
            },
        ],
    },
    {
        recordedOn: '2026-08-21',
        tier: 21,
        participants: 47,
        hrid: '/monsters/trial_hedgehog',
        combatDetails: {
            maxHitpoints: 1822800,
            maxManapoints: 1240000,
            attackInterval: 1344688480,
            totalCastSpeed: 1.09,
            stabAccuracyRating: 310,
            slashAccuracyRating: 310,
            smashAccuracyRating: 1178,
            rangedAccuracyRating: 310,
            magicAccuracyRating: 1178,
            defensiveMaxDamage: 806,
            stabMaxDamage: 310,
            slashMaxDamage: 310,
            smashMaxDamage: 806,
            rangedMaxDamage: 10,
            magicMaxDamage: 806,
            stabEvasionRating: 1395,
            slashEvasionRating: 1395,
            smashEvasionRating: 1395,
            rangedEvasionRating: 1395,
            magicEvasionRating: 1395,
            totalArmor: 810,
            totalWaterResistance: 810,
            totalNatureResistance: 810,
            totalFireResistance: 480,
            totalThreat: 100,
            staminaLevel: 300,
            intelligenceLevel: 300,
            attackLevel: 300,
            meleeLevel: 300,
            defenseLevel: 300,
            rangedLevel: 0,
            magicLevel: 300,
            combatStats: {
                abilityHaste: 94,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/guardian_aura',
                level: 120,
                availableAfterSeconds: 30.928,
            },
            {
                abilityHrid: '/abilities/toughness',
                level: 180,
                availableAfterSeconds: 7.732,
            },
            {
                abilityHrid: '/abilities/spike_shell',
                level: 180,
                availableAfterSeconds: 7.732,
            },
            {
                abilityHrid: '/abilities/natures_veil',
                level: 180,
                availableAfterSeconds: 3.866,
            },
            {
                abilityHrid: '/abilities/fracturing_impact',
                level: 180,
                availableAfterSeconds: 5.155,
            },
        ],
    },
    {
        recordedOn: '2026-08-25',
        tier: 1,
        participants: 55,
        hrid: '/monsters/trial_badger',
        combatDetails: {
            maxHitpoints: 588225,
            maxManapoints: 379500,
            attackInterval: 1224489795,
            totalCastSpeed: 1.1500000000000001,
            stabAccuracyRating: 110,
            slashAccuracyRating: 462,
            smashAccuracyRating: 110,
            rangedAccuracyRating: 110,
            magicAccuracyRating: 110,
            defensiveMaxDamage: 110,
            stabMaxDamage: 110,
            slashMaxDamage: 264,
            smashMaxDamage: 110,
            rangedMaxDamage: 10,
            magicMaxDamage: 10,
            stabEvasionRating: 517,
            slashEvasionRating: 517,
            smashEvasionRating: 517,
            rangedEvasionRating: 660,
            magicEvasionRating: 374,
            totalArmor: 420,
            totalWaterResistance: 170,
            totalNatureResistance: 170,
            totalFireResistance: 170,
            totalThreat: 100,
            staminaLevel: 100,
            intelligenceLevel: 100,
            attackLevel: 100,
            meleeLevel: 100,
            defenseLevel: 100,
            rangedLevel: 0,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 110,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/fierce_aura',
                level: 40,
                availableAfterSeconds: 28.571,
            },
            {
                abilityHrid: '/abilities/berserk',
                level: 60,
                availableAfterSeconds: 7.142,
            },
            {
                abilityHrid: '/abilities/maim',
                level: 60,
                availableAfterSeconds: 4.761,
            },
            {
                abilityHrid: '/abilities/cleave',
                level: 60,
                availableAfterSeconds: 4.761,
            },
            {
                abilityHrid: '/abilities/scratch',
                level: 60,
                availableAfterSeconds: 3.571,
            },
        ],
    },
    {
        recordedOn: '2026-08-25',
        tier: 1,
        participants: 55,
        hrid: '/monsters/trial_badger',
        combatDetails: {
            maxHitpoints: 588225,
            maxManapoints: 379500,
            attackInterval: 1224489795,
            totalCastSpeed: 1.1500000000000001,
            stabAccuracyRating: 110,
            slashAccuracyRating: 462,
            smashAccuracyRating: 110,
            rangedAccuracyRating: 110,
            magicAccuracyRating: 110,
            defensiveMaxDamage: 110,
            stabMaxDamage: 110,
            slashMaxDamage: 264,
            smashMaxDamage: 110,
            rangedMaxDamage: 10,
            magicMaxDamage: 10,
            stabEvasionRating: 517,
            slashEvasionRating: 517,
            smashEvasionRating: 517,
            rangedEvasionRating: 660,
            magicEvasionRating: 374,
            totalArmor: 420,
            totalWaterResistance: 170,
            totalNatureResistance: 170,
            totalFireResistance: 170,
            totalThreat: 100,
            staminaLevel: 100,
            intelligenceLevel: 100,
            attackLevel: 100,
            meleeLevel: 100,
            defenseLevel: 100,
            rangedLevel: 0,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 110,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/fierce_aura',
                level: 40,
                availableAfterSeconds: 28.571,
            },
            {
                abilityHrid: '/abilities/berserk',
                level: 60,
                availableAfterSeconds: 7.142,
            },
            {
                abilityHrid: '/abilities/maim',
                level: 60,
                availableAfterSeconds: 4.761,
            },
            {
                abilityHrid: '/abilities/cleave',
                level: 60,
                availableAfterSeconds: 4.761,
            },
            {
                abilityHrid: '/abilities/scratch',
                level: 60,
                availableAfterSeconds: 3.571,
            },
        ],
    },
    {
        recordedOn: '2026-08-25',
        tier: 14,
        participants: 55,
        hrid: '/monsters/trial_badger',
        combatDetails: {
            maxHitpoints: 1283400,
            maxManapoints: 828000,
            attackInterval: 1153106982,
            totalCastSpeed: 1.215,
            stabAccuracyRating: 240,
            slashAccuracyRating: 1008,
            smashAccuracyRating: 240,
            rangedAccuracyRating: 240,
            magicAccuracyRating: 240,
            defensiveMaxDamage: 240,
            stabMaxDamage: 240,
            slashMaxDamage: 576,
            smashMaxDamage: 240,
            rangedMaxDamage: 10,
            magicMaxDamage: 10,
            stabEvasionRating: 1128,
            slashEvasionRating: 1128,
            smashEvasionRating: 1128,
            rangedEvasionRating: 1440,
            magicEvasionRating: 816,
            totalArmor: 966,
            totalWaterResistance: 391,
            totalNatureResistance: 391,
            totalFireResistance: 391,
            totalThreat: 100,
            staminaLevel: 230,
            intelligenceLevel: 230,
            attackLevel: 230,
            meleeLevel: 230,
            defenseLevel: 230,
            rangedLevel: 0,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 110,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/fierce_aura',
                level: 92,
                availableAfterSeconds: 28.572,
            },
            {
                abilityHrid: '/abilities/berserk',
                level: 138,
                availableAfterSeconds: 7.143,
            },
            {
                abilityHrid: '/abilities/maim',
                level: 138,
                availableAfterSeconds: 4.762,
            },
            {
                abilityHrid: '/abilities/cleave',
                level: 138,
                availableAfterSeconds: 4.762,
            },
            {
                abilityHrid: '/abilities/scratch',
                level: 138,
                availableAfterSeconds: 3.572,
            },
        ],
    },
    {
        recordedOn: '2026-08-25',
        tier: 14,
        participants: 55,
        hrid: '/monsters/trial_badger',
        combatDetails: {
            maxHitpoints: 1283400,
            maxManapoints: 828000,
            attackInterval: 1153106982,
            totalCastSpeed: 1.215,
            stabAccuracyRating: 240,
            slashAccuracyRating: 1008,
            smashAccuracyRating: 240,
            rangedAccuracyRating: 240,
            magicAccuracyRating: 240,
            defensiveMaxDamage: 240,
            stabMaxDamage: 240,
            slashMaxDamage: 576,
            smashMaxDamage: 240,
            rangedMaxDamage: 10,
            magicMaxDamage: 10,
            stabEvasionRating: 1128,
            slashEvasionRating: 1128,
            smashEvasionRating: 1128,
            rangedEvasionRating: 1440,
            magicEvasionRating: 816,
            totalArmor: 966,
            totalWaterResistance: 391,
            totalNatureResistance: 391,
            totalFireResistance: 391,
            totalThreat: 100,
            staminaLevel: 230,
            intelligenceLevel: 230,
            attackLevel: 230,
            meleeLevel: 230,
            defenseLevel: 230,
            rangedLevel: 0,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 110,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/fierce_aura',
                level: 92,
                availableAfterSeconds: 28.572,
            },
            {
                abilityHrid: '/abilities/berserk',
                level: 138,
                availableAfterSeconds: 7.143,
            },
            {
                abilityHrid: '/abilities/maim',
                level: 138,
                availableAfterSeconds: 4.762,
            },
            {
                abilityHrid: '/abilities/cleave',
                level: 138,
                availableAfterSeconds: 4.762,
            },
            {
                abilityHrid: '/abilities/scratch',
                level: 138,
                availableAfterSeconds: 3.572,
            },
        ],
    },
    {
        recordedOn: '2026-08-29',
        tier: 1,
        participants: 53,
        hrid: '/monsters/trial_beetle',
        combatDetails: {
            maxHitpoints: 336600,
            maxManapoints: 220000,
            attackInterval: 1063337956,
            totalCastSpeed: 1.11,
            stabAccuracyRating: 110,
            slashAccuracyRating: 110,
            smashAccuracyRating: 330,
            rangedAccuracyRating: 110,
            magicAccuracyRating: 110,
            defensiveMaxDamage: 110,
            stabMaxDamage: 110,
            slashMaxDamage: 110,
            smashMaxDamage: 165,
            rangedMaxDamage: 10,
            magicMaxDamage: 10,
            stabEvasionRating: 550,
            slashEvasionRating: 550,
            smashEvasionRating: 429,
            rangedEvasionRating: 550,
            magicEvasionRating: 429,
            totalArmor: 420,
            totalWaterResistance: 220,
            totalNatureResistance: 320,
            totalFireResistance: 320,
            totalThreat: 100,
            staminaLevel: 100,
            intelligenceLevel: 100,
            attackLevel: 100,
            meleeLevel: 100,
            defenseLevel: 100,
            rangedLevel: 0,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 106,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/invincible',
                level: 40,
                availableAfterSeconds: 21.845,
            },
            {
                abilityHrid: '/abilities/toughness',
                level: 60,
                availableAfterSeconds: 7.281,
            },
            {
                abilityHrid: '/abilities/fracturing_impact',
                level: 60,
                availableAfterSeconds: 4.854,
            },
            {
                abilityHrid: '/abilities/stunning_blow',
                level: 60,
                availableAfterSeconds: 4.854,
            },
            {
                abilityHrid: '/abilities/sweep',
                level: 60,
                availableAfterSeconds: 4.854,
            },
        ],
    },
    {
        recordedOn: '2026-08-29',
        tier: 1,
        participants: 53,
        hrid: '/monsters/trial_dragonfly',
        combatDetails: {
            maxHitpoints: 336600,
            maxManapoints: 220000,
            attackInterval: 1248266296,
            totalCastSpeed: 1.11,
            stabAccuracyRating: 110,
            slashAccuracyRating: 110,
            smashAccuracyRating: 110,
            rangedAccuracyRating: 505.99999999999994,
            magicAccuracyRating: 110,
            defensiveMaxDamage: 110,
            stabMaxDamage: 10,
            slashMaxDamage: 10,
            smashMaxDamage: 10,
            rangedMaxDamage: 143,
            magicMaxDamage: 10,
            stabEvasionRating: 352,
            slashEvasionRating: 352,
            smashEvasionRating: 352,
            rangedEvasionRating: 473,
            magicEvasionRating: 616,
            totalArmor: 140,
            totalWaterResistance: 220,
            totalNatureResistance: 220,
            totalFireResistance: 220,
            totalThreat: 100,
            staminaLevel: 100,
            intelligenceLevel: 100,
            attackLevel: 100,
            meleeLevel: 0,
            defenseLevel: 100,
            rangedLevel: 100,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 106,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/critical_aura',
                level: 40,
                availableAfterSeconds: 29.126,
            },
            {
                abilityHrid: '/abilities/precision',
                level: 60,
                availableAfterSeconds: 7.281,
            },
            {
                abilityHrid: '/abilities/steady_shot',
                level: 60,
                availableAfterSeconds: 4.854,
            },
            {
                abilityHrid: '/abilities/rain_of_arrows',
                level: 60,
                availableAfterSeconds: 4.854,
            },
            {
                abilityHrid: '/abilities/pestilent_shot',
                level: 60,
                availableAfterSeconds: 4.854,
            },
        ],
    },
    {
        recordedOn: '2026-08-29',
        tier: 1,
        participants: 53,
        hrid: '/monsters/trial_wasp',
        combatDetails: {
            maxHitpoints: 336600,
            maxManapoints: 220000,
            attackInterval: 1202034211,
            totalCastSpeed: 1.11,
            stabAccuracyRating: 473,
            slashAccuracyRating: 110,
            smashAccuracyRating: 110,
            rangedAccuracyRating: 110,
            magicAccuracyRating: 110,
            defensiveMaxDamage: 110,
            stabMaxDamage: 132,
            slashMaxDamage: 110,
            smashMaxDamage: 110,
            rangedMaxDamage: 10,
            magicMaxDamage: 10,
            stabEvasionRating: 473,
            slashEvasionRating: 473,
            smashEvasionRating: 473,
            rangedEvasionRating: 605,
            magicEvasionRating: 352,
            totalArmor: 200,
            totalWaterResistance: 120,
            totalNatureResistance: 120,
            totalFireResistance: 120,
            totalThreat: 100,
            staminaLevel: 100,
            intelligenceLevel: 100,
            attackLevel: 100,
            meleeLevel: 100,
            defenseLevel: 100,
            rangedLevel: 0,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 106,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/fierce_aura',
                level: 40,
                availableAfterSeconds: 29.126,
            },
            {
                abilityHrid: '/abilities/frenzy',
                level: 60,
                availableAfterSeconds: 7.282,
            },
            {
                abilityHrid: '/abilities/penetrating_strike',
                level: 60,
                availableAfterSeconds: 4.854,
            },
            {
                abilityHrid: '/abilities/puncture',
                level: 60,
                availableAfterSeconds: 4.854,
            },
            {
                abilityHrid: '/abilities/impale',
                level: 60,
                availableAfterSeconds: 4.854,
            },
        ],
    },
    {
        recordedOn: '2026-08-29',
        tier: 1,
        participants: 53,
        hrid: '/monsters/trial_firefly',
        combatDetails: {
            maxHitpoints: 336600,
            maxManapoints: 220000,
            attackInterval: 1386962551,
            totalCastSpeed: 1.11,
            stabAccuracyRating: 110,
            slashAccuracyRating: 110,
            smashAccuracyRating: 110,
            rangedAccuracyRating: 110,
            magicAccuracyRating: 462,
            defensiveMaxDamage: 110,
            stabMaxDamage: 10,
            slashMaxDamage: 10,
            smashMaxDamage: 10,
            rangedMaxDamage: 10,
            magicMaxDamage: 154,
            stabEvasionRating: 660,
            slashEvasionRating: 660,
            smashEvasionRating: 660,
            rangedEvasionRating: 352,
            magicEvasionRating: 473,
            totalArmor: 120,
            totalWaterResistance: 140,
            totalNatureResistance: 200,
            totalFireResistance: 200,
            totalThreat: 100,
            staminaLevel: 100,
            intelligenceLevel: 100,
            attackLevel: 100,
            meleeLevel: 0,
            defenseLevel: 100,
            rangedLevel: 0,
            magicLevel: 100,
            combatStats: {
                abilityHaste: 106,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/mystic_aura',
                level: 40,
                availableAfterSeconds: 29.126,
            },
            {
                abilityHrid: '/abilities/elemental_affinity',
                level: 60,
                availableAfterSeconds: 7.282,
            },
            {
                abilityHrid: '/abilities/firestorm',
                level: 60,
                availableAfterSeconds: 3.641,
            },
            {
                abilityHrid: '/abilities/smoke_burst',
                level: 60,
                availableAfterSeconds: 3.641,
            },
            {
                abilityHrid: '/abilities/fireball',
                level: 60,
                availableAfterSeconds: 0,
            },
        ],
    },
    {
        recordedOn: '2026-08-31',
        tier: 16,
        participants: 56,
        hrid: '/monsters/trial_chameleon',
        combatDetails: {
            maxHitpoints: 2332200,
            maxManapoints: 1495000,
            attackInterval: 1132075471,
            totalCastSpeed: 1.245,
            stabAccuracyRating: 260,
            slashAccuracyRating: 260,
            smashAccuracyRating: 260,
            rangedAccuracyRating: 1196,
            magicAccuracyRating: 260,
            defensiveMaxDamage: 260,
            stabMaxDamage: 10,
            slashMaxDamage: 10,
            smashMaxDamage: 10,
            rangedMaxDamage: 910,
            magicMaxDamage: 10,
            stabEvasionRating: 936,
            slashEvasionRating: 936,
            smashEvasionRating: 936,
            rangedEvasionRating: 1222,
            magicEvasionRating: 1456,
            totalArmor: 612.5,
            totalWaterResistance: 1050,
            totalNatureResistance: 1050,
            totalFireResistance: 1050,
            totalThreat: 100,
            staminaLevel: 250,
            intelligenceLevel: 250,
            attackLevel: 250,
            meleeLevel: 0,
            defenseLevel: 250,
            rangedLevel: 250,
            magicLevel: 0,
            combatStats: {
                abilityHaste: 112,
            },
        },
        combatAbilities: [
            {
                abilityHrid: '/abilities/critical_aura',
                level: 100,
                availableAfterSeconds: 28.302,
            },
            {
                abilityHrid: '/abilities/precision',
                level: 150,
                availableAfterSeconds: 7.076,
            },
            {
                abilityHrid: '/abilities/penetrating_shot',
                level: 150,
                availableAfterSeconds: 4.717,
            },
            {
                abilityHrid: '/abilities/rain_of_arrows',
                level: 150,
                availableAfterSeconds: 4.717,
            },
            {
                abilityHrid: '/abilities/steady_shot',
                level: 150,
                availableAfterSeconds: 4.717,
            },
        ],
    },
];

export const RECORDED_SKILLING_CURVES = [
    {
        recordedOn: '2026-08-17',
        skill: 'milking',
        effectiveLevel: 101,
        successBonus: 0,
        participants: 30,
        readings: [
            {
                tier: 1,
                successRate: 0.804,
                targetWorkValue: 52000,
            },
            {
                tier: 2,
                successRate: 0.728,
                targetWorkValue: 57200,
            },
            {
                tier: 3,
                successRate: 0.648,
                targetWorkValue: 62400,
            },
            {
                tier: 4,
                successRate: 0.568,
                targetWorkValue: 67600,
            },
            {
                tier: 5,
                successRate: 0.488,
                targetWorkValue: 72800,
            },
            {
                tier: 6,
                successRate: 0.408,
                targetWorkValue: 78000,
            },
            {
                tier: 7,
                successRate: 0.32799999999999996,
                targetWorkValue: 83200,
            },
            {
                tier: 8,
                successRate: 0.248,
                targetWorkValue: 88400,
            },
            {
                tier: 9,
                successRate: 0.168,
                targetWorkValue: 93600,
            },
            {
                tier: 10,
                successRate: 0.08800000000000001,
                targetWorkValue: 98800,
            },
            {
                tier: 11,
                successRate: 0.05,
                targetWorkValue: 104000,
            },
        ],
    },
    {
        recordedOn: '2026-08-21',
        skill: 'alchemy',
        effectiveLevel: 107,
        successBonus: 0,
        participants: 1,
        readings: [
            {
                tier: 1,
                successRate: 0.828,
                targetWorkValue: 40400,
            },
            {
                tier: 2,
                successRate: 0.7759999999999999,
                targetWorkValue: 44440,
            },
            {
                tier: 3,
                successRate: 0.696,
                targetWorkValue: 48480,
            },
        ],
    },
    {
        recordedOn: '2026-08-25',
        skill: 'cheesesmithing',
        effectiveLevel: 106,
        successBonus: 0,
        participants: 30,
        readings: [
            {
                tier: 1,
                successRate: 0.8240000000000001,
                targetWorkValue: 52000,
            },
            {
                tier: 2,
                successRate: 0.768,
                targetWorkValue: 57200,
            },
            {
                tier: 3,
                successRate: 0.688,
                targetWorkValue: 62400,
            },
            {
                tier: 4,
                successRate: 0.608,
                targetWorkValue: 67600,
            },
            {
                tier: 5,
                successRate: 0.528,
                targetWorkValue: 72800,
            },
            {
                tier: 6,
                successRate: 0.44799999999999995,
                targetWorkValue: 78000,
            },
            {
                tier: 7,
                successRate: 0.368,
                targetWorkValue: 83200,
            },
            {
                tier: 8,
                successRate: 0.28800000000000003,
                targetWorkValue: 88400,
            },
            {
                tier: 9,
                successRate: 0.20800000000000002,
                targetWorkValue: 93600,
            },
            {
                tier: 10,
                successRate: 0.128,
                targetWorkValue: 98800,
            },
            {
                tier: 11,
                successRate: 0.05,
                targetWorkValue: 104000,
            },
            {
                tier: 12,
                successRate: 0.05,
                targetWorkValue: 109200,
            },
        ],
    },
    {
        recordedOn: '2026-08-31',
        skill: 'cheesesmithing',
        effectiveLevel: 108,
        successBonus: 0,
        participants: 27,
        readings: [
            {
                tier: 1,
                successRate: 0.8320000000000001,
                targetWorkValue: 50800,
            },
            {
                tier: 2,
                successRate: 0.784,
                targetWorkValue: 55880,
            },
            {
                tier: 3,
                successRate: 0.7040000000000001,
                targetWorkValue: 60960,
            },
            {
                tier: 4,
                successRate: 0.624,
                targetWorkValue: 66040,
            },
            {
                tier: 5,
                successRate: 0.544,
                targetWorkValue: 71120,
            },
            {
                tier: 6,
                successRate: 0.46399999999999997,
                targetWorkValue: 76200,
            },
            {
                tier: 7,
                successRate: 0.384,
                targetWorkValue: 81280,
            },
            {
                tier: 8,
                successRate: 0.304,
                targetWorkValue: 86360,
            },
            {
                tier: 9,
                successRate: 0.22399999999999998,
                targetWorkValue: 91440,
            },
            {
                tier: 10,
                successRate: 0.14400000000000002,
                targetWorkValue: 96520,
            },
            {
                tier: 11,
                successRate: 0.064,
                targetWorkValue: 101600,
            },
            {
                tier: 12,
                successRate: 0.05,
                targetWorkValue: 106680,
            },
        ],
    },
    {
        recordedOn: '2026-09-07',
        skill: 'enhancing',
        effectiveLevel: 103,
        successBonus: 0.045,
        participants: 30,
        readings: [
            {
                tier: 1,
                successRate: 0.848,
                targetWorkValue: 52000,
            },
            {
                tier: 2,
                successRate: 0.78,
                targetWorkValue: 57200,
            },
            {
                tier: 3,
                successRate: 0.7,
                targetWorkValue: 62400,
            },
            {
                tier: 4,
                successRate: 0.62,
                targetWorkValue: 67600,
            },
            {
                tier: 5,
                successRate: 0.54,
                targetWorkValue: 72800,
            },
            {
                tier: 6,
                successRate: 0.46,
                targetWorkValue: 78000,
            },
            {
                tier: 7,
                successRate: 0.38,
                targetWorkValue: 83200,
            },
            {
                tier: 8,
                successRate: 0.3,
                targetWorkValue: 88400,
            },
            {
                tier: 9,
                successRate: 0.22,
                targetWorkValue: 93600,
            },
            {
                tier: 10,
                successRate: 0.14,
                targetWorkValue: 98800,
            },
            {
                tier: 11,
                successRate: 0.06,
                targetWorkValue: 104000,
            },
        ],
    },
];
