/** @vitest-environment happy-dom
 *
 * How the Lab Sim asks for a house room.
 *
 * A room level used to be the one upgrade the labyrinth analyses could not
 * install for themselves: the shared candidate applier knew equipment,
 * abilities, skill levels, shrines and drinks, and a house candidate handed to
 * it fell through to the equipment write — so the simulation ran the unchanged
 * character and the row came back a confident +0.00%. The panel worked around
 * that with a pass of its own, and the dimension was Configure-fight only
 * because a pass of its own is not something the whole-run analysis has.
 *
 * The applier has a house branch now, the private pass is gone, and this file
 * is about the panel's half of that: that a house room is generated by the same
 * generator every other candidate set uses, that it reaches every scope, and
 * that an empty result still explains itself. That the raised level actually
 * lands on the simulated character is asserted end to end, against the real
 * advisor, in `lab-sim-ui.test.js`.
 */

import { describe, test, expect, beforeEach, vi } from 'vitest';

const advisor = vi.hoisted(() => ({
    houseCandidates: [],
    scan: { rooms: 0, withBuffs: 0, combatRelevant: 0, belowCap: 0 },
    generateCalls: [],
}));

vi.mock('../../core/config.js', () => ({
    default: { getSetting: () => false, getSettingValue: (_k, d) => d, setSetting: () => {} },
}));
vi.mock('../../core/data-manager.js', () => ({
    default: {
        getInitClientData: () => ({ abilityDetailMap: {} }),
        getInventory: () => [],
        getItemDetails: () => null,
        characterItems: [],
        characterEquipment: new Map(),
        characterData: { characterAbilities: [] },
    },
}));

vi.mock('./combat-sim-ui.js', () => ({
    default: {
        upgradeRowPurchase: () => null,
        upgradeRowActionsHtml: () => '',
        wireUpgradeRowActions: () => {},
    },
}));

vi.mock('./combat-sim-adapter.js', () => ({
    buildGameDataPayload: () => ({ itemDetailMap: {}, houseRoomDetailMap: {} }),
    buildAllPlayerDTOs: async () => ({ players: [] }),
    getCombatZones: () => [{ hrid: '/actions/combat/fly' }],
    getCommunityBuffs: () => ({}),
    getLabyrinthMonsters: () => [],
}));

vi.mock('./combat-sim-runner.js', () => ({
    runLabyrinthSimulation: async () => ({ labyAttemptCount: 200, encounters: 100 }),
    cancelSimulation: () => {},
    getMaxWorkers: () => 2,
}));

// The generator is the whole point: a house candidate has to come out of the
// same `generateCandidates` call every other set does, under its own mode name,
// rather than out of a private branch in the panel.
vi.mock('./upgrade-advisor.js', () => ({
    runLabyrinthUpgradeAnalysis: async () => ({ baseline: null, results: [] }),
    runLabyrinthAllFightsAnalysis: async () => ({ baseline: null, results: [] }),
    computeSkillingClearRatesFromEditor: async () => ({}),
    runSkillingUpgradeAnalysis: async () => ({ results: [] }),
    getStyleExcludedSkills: () => [],
    planWithinBudget: () => ({ picks: [], skipped: [], totalCost: 0, attemptsSaved: 0 }),
    runLabyrinthCombinationCheck: async () => ({}),
    generateCandidates: (_dto, _gameData, mode) => {
        advisor.generateCalls.push(mode);
        return mode === 'house' ? advisor.houseCandidates.map((c) => ({ ...c })) : [];
    },
    generateHouseCandidates: () => advisor.houseCandidates.map((c) => ({ ...c })),
    describeHouseScan: () => advisor.scan,
}));

const { default: ui } = await import('./lab-sim-ui.js');
const { planLabUpgradeRun, labDimensionAvailability } = await import('./lab-sim-upgrade-modes.js');

const DAIRY = '/house_rooms/dairy_barn';
const GARDEN = '/house_rooms/garden';

const room = (roomHrid, currentLevel, upgradeLevel, name) => ({
    type: 'house',
    slot: `house|${roomHrid}`,
    roomHrid,
    currentLevel,
    upgradeLevel,
    description: `${name} Lv${currentLevel} → Lv${upgradeLevel}`,
});

const player = (houseRooms = {}) => ({ hrid: 'p1', equipment: {}, abilities: [], houseRooms });
const gameData = { itemDetailMap: {}, houseRoomDetailMap: {} };

beforeEach(() => {
    ui._upgradeAborted = false;
    advisor.generateCalls = [];
    advisor.houseCandidates = [room(DAIRY, 4, 5, 'Dairy Barn'), room(GARDEN, 2, 3, 'Garden')];
    advisor.scan = { rooms: 20, withBuffs: 18, combatRelevant: 11, belowCap: 2 };
});

describe('a house room is generated the way every other candidate set is', () => {
    test('the single-fight analysis is handed them as extra candidates, under the house mode', () => {
        const candidates = ui._extraDimensionCandidates(['house'], player({ [DAIRY]: 4, [GARDEN]: 2 }), gameData);

        expect(advisor.generateCalls).toEqual(['house']);
        expect(candidates.map((c) => c.roomHrid)).toEqual([DAIRY, GARDEN]);
        expect(candidates.every((c) => c.type === 'house')).toBe(true);
    });

    test('and they carry the level to install, which is what the applier now writes', () => {
        const candidates = ui._extraDimensionCandidates(['house'], player({ [DAIRY]: 4 }), gameData);

        expect(candidates.find((c) => c.roomHrid === DAIRY)).toMatchObject({ currentLevel: 4, upgradeLevel: 5 });
    });

    test('a scope with nothing checked asks the generator for nothing', () => {
        expect(ui._extraDimensionCandidates([], player(), gameData)).toEqual([]);
        expect(advisor.generateCalls).toEqual([]);
    });
});

describe('every target scope can be asked about a house room', () => {
    test('the Configure fight ranks them beside whatever else is checked', () => {
        const plan = planLabUpgradeRun({
            dimensions: ['equipment', 'house'],
            scopeMode: 'current',
            configureMonsterHrid: '/monsters/mimic',
        });

        expect(plan).toMatchObject({ kind: 'single', upgradeMode: 'equipment', extraModes: ['house'], dropped: [] });
    });

    test('a whole run weighs each fight’s own exposure to the same room level', () => {
        const plan = planLabUpgradeRun({
            dimensions: ['house'],
            scopeMode: 'all',
            allMonsters: ['/monsters/mimic', '/monsters/eye_watcher'],
        });

        expect(plan).toMatchObject({ kind: 'allFights', modes: ['house'], dropped: [] });
        expect(plan.monsterHrids).toHaveLength(2);
    });

    test('a chosen subset does too', () => {
        const plan = planLabUpgradeRun({
            dimensions: ['house'],
            scopeMode: 'selected',
            chosenMonsters: ['/monsters/mimic'],
            allMonsters: ['/monsters/mimic', '/monsters/eye_watcher'],
        });

        expect(plan).toMatchObject({ kind: 'allFights', modes: ['house'], monsterHrids: ['/monsters/mimic'] });
    });

    test('and nothing is left refusing them on the availability rules', () => {
        for (const scope of ['current', 'all', 'selected']) {
            expect(labDimensionAvailability(scope, 8).house).toEqual({ enabled: true, reason: '' });
        }
    });
});

describe('when there is nothing to weigh', () => {
    test('rooms that exist say nothing — the table speaks for itself', () => {
        expect(ui._describeHouseScan(player({ [DAIRY]: 4 }), gameData)).toBe('');
    });

    test('every combat room already maxed says so rather than reading as no upgrades', () => {
        advisor.houseCandidates = [];
        advisor.scan = { rooms: 20, withBuffs: 18, combatRelevant: 11, belowCap: 0 };

        expect(ui._describeHouseScan(player(), gameData)).toMatch(/all 11 combat house rooms are already maxed/);
    });

    test('and a game with no combat-relevant rooms is a different answer', () => {
        advisor.houseCandidates = [];
        advisor.scan = { rooms: 20, withBuffs: 18, combatRelevant: 0, belowCap: 0 };

        expect(ui._describeHouseScan(player(), gameData)).toMatch(/no combat-relevant house rooms/);
    });

    test('and no game data at all is not an answer worth printing', () => {
        expect(ui._describeHouseScan(player(), null)).toBe('');
    });
});
