import { describe, it, expect } from 'vitest';
import { wilsonInterval } from '../combat-sim/engine/wilson.js';
import {
    emptyTally,
    foldReading,
    healthOf,
    isFuryEntry,
    observeBuffs,
    poolBoosts,
    readMetric,
    readUnit,
    summarize,
    FURY_ALARM_READINGS,
    MIN_READINGS,
    MIN_GAP_UNITS,
} from './fury-stacking.js';

const LEVEL = 100;
const GEAR = 0.5;
/** (10 + level) × (1 + gear ratio) — the base every style here is built from. */
const BASE = (10 + LEVEL) * (1 + GEAR);

const STYLES = ['stab', 'slash', 'smash', 'ranged', 'magic'];

/**
 * The factor one model puts on the base.
 * @param {string} model - 'multiplicative' or 'additive'
 * @param {number} d - Non-Fury ratio boost
 * @param {number} f - Fury ratio boost
 * @returns {number} The factor
 */
function factor(model, d, f) {
    return model === 'multiplicative' ? (1 + d) * (1 + f) : 1 + d + f;
}

/**
 * A synthetic player snapshot whose resolved numbers were generated by a known
 * model, so the check's verdict is checkable against the truth that made it.
 *
 * `scale` deliberately breaks both models at once, for the reading that should
 * match neither.
 *
 * @param {Object} spec - What to build
 * @param {{d: number, f: number, model?: string, scale?: number}} spec.acc - Accuracy terms
 * @param {{d: number, f: number, model?: string, scale?: number}} spec.dmg - Damage terms
 * @param {number} [spec.accFlat] - A flat boost on the accuracy buff type
 * @param {boolean} [spec.engineTypes] - Type the Fury entries the way the sim
 *   engine synthesizes them instead of the way the wire states them
 * @param {boolean} [spec.noBuffMap] - Leave the snapshot's buff map off entirely
 * @returns {Object} A unit with `combatDetails` and `combatBuffMap`
 */
function buildUnit({ acc, dmg, accFlat = 0, engineTypes = false, noBuffMap = false }) {
    const accFactor = factor(acc.model || 'multiplicative', acc.d, acc.f) * (acc.scale ?? 1);
    const dmgFactor = factor(dmg.model || 'multiplicative', dmg.d, dmg.f) * (dmg.scale ?? 1);

    const combatStats = { defensiveDamage: 0 };
    const combatDetails = {
        attackLevel: LEVEL,
        meleeLevel: LEVEL,
        rangedLevel: LEVEL,
        magicLevel: LEVEL,
        defenseLevel: LEVEL,
        combatStats,
    };
    for (const style of STYLES) {
        combatStats[`${style}Accuracy`] = GEAR;
        combatStats[`${style}Damage`] = GEAR;
        combatDetails[`${style}AccuracyRating`] = Math.round(BASE * accFactor);
        combatDetails[`${style}MaxDamage`] = Math.round(BASE * dmgFactor);
    }
    combatDetails.defensiveMaxDamage = Math.round((10 + LEVEL) * dmgFactor);

    if (noBuffMap) return { isPlayer: true, combatDetails };

    return { isPlayer: true, combatDetails, combatBuffMap: buffMap({ acc, dmg, accFlat, engineTypes }) };
}

/**
 * A live buff map in the shape the wire states one.
 *
 * Keyed by unique hrid, each record repeating its own `uniqueHrid` and carrying
 * `{typeHrid, ratioBoost, flatBoost}` — the shape `combat-unit-buff-bars.js`
 * reads chips out of and `monster-stat-check.js` folds into the sim. Fury's two
 * effects are named `/buff_uniques/fury_accuracy` and `/buff_uniques/fury_damage`
 * there; `/buff_types/fury_accuracy` is the sim engine's own synthetic type and
 * `engineTypes` is what builds that variant, so both are covered.
 *
 * @param {Object} spec - Terms
 * @param {{d: number, f: number}} spec.acc - Accuracy terms
 * @param {{d: number, f: number}} spec.dmg - Damage terms
 * @param {number} [spec.accFlat] - A flat boost on the accuracy buff type
 * @param {boolean} [spec.engineTypes] - Use the engine's synthetic Fury types
 * @returns {Object} A `combatBuffMap`
 */
function buffMap({ acc, dmg, accFlat = 0, engineTypes = false }) {
    const entry = (uniqueHrid, typeHrid, ratioBoost, flatBoost = 0) => [
        uniqueHrid,
        { uniqueHrid, typeHrid, ratioBoost, flatBoost },
    ];
    return Object.fromEntries([
        entry('/buff_uniques/precision', '/buff_types/accuracy', acc.d, accFlat),
        entry('/buff_uniques/berserk', '/buff_types/damage', dmg.d),
        entry('/buff_uniques/fury_accuracy', engineTypes ? '/buff_types/fury_accuracy' : '/buff_types/accuracy', acc.f),
        entry('/buff_uniques/fury_damage', engineTypes ? '/buff_types/fury_damage' : '/buff_types/damage', dmg.f),
    ]);
}

/** A pair of terms wide enough that the two models cannot both be satisfied. */
const WIDE = { d: 0.5, f: 0.4 };

describe('finding Fury in a live buff map', () => {
    it('totals every buff of a type, the way the engine does', () => {
        const map = {
            a: { uniqueHrid: '/buff_uniques/berserk', typeHrid: '/buff_types/damage', ratioBoost: 0.1, flatBoost: 0 },
            b: { uniqueHrid: '/buff_uniques/rage', typeHrid: '/buff_types/damage', ratioBoost: 0.2, flatBoost: 3 },
            c: {
                uniqueHrid: '/buff_uniques/precision',
                typeHrid: '/buff_types/accuracy',
                ratioBoost: 0.9,
                flatBoost: 0,
            },
        };
        const damage = poolBoosts(map, 'damage');
        expect(damage.other).toEqual({ ratio: 0.30000000000000004, flat: 3 });
        expect(damage.fury).toEqual({ ratio: 0, flat: 0 });
        expect(damage.entries).toBe(3);
        expect(damage.furyEntries).toBe(0);
    });

    it('recognises Fury by the name the wire gives it, not only by the sim engine type', () => {
        // The bug this check shipped with: the live entry is keyed by its
        // unique hrid and types itself as the ordinary accuracy buff, so a
        // lookup for `/buff_types/fury_accuracy` — a value only the sim engine
        // ever produces — found nothing and filed every reading as "no Fury"
        const map = buffMap({ acc: { d: 0.5, f: 0.4 }, dmg: { d: 0.5, f: 0.4 } });
        expect(map['/buff_uniques/fury_accuracy'].typeHrid).toBe('/buff_types/accuracy');

        const pool = poolBoosts(map, 'accuracy');
        expect(pool.furyEntries).toBe(1);
        expect(pool.fury.ratio).toBeCloseTo(0.4, 10);
        // …and it is not also counted in the other pool, which would compare
        // the two models using the same number twice
        expect(pool.other.ratio).toBeCloseTo(0.5, 10);
    });

    it('still recognises the sim engine’s own synthetic Fury type', () => {
        const map = buffMap({ acc: { d: 0.5, f: 0.4 }, dmg: { d: 0.5, f: 0.4 }, engineTypes: true });
        const pool = poolBoosts(map, 'accuracy');
        expect(pool.fury.ratio).toBeCloseTo(0.4, 10);
        expect(pool.other.ratio).toBeCloseTo(0.5, 10);
    });

    it('does not mistake another buff for Fury’s', () => {
        expect(isFuryEntry('/buff_uniques/fury_accuracy', '/buff_types/accuracy', 'accuracy')).toBe(true);
        expect(isFuryEntry('/buff_uniques/fury_damage', '/buff_types/damage', 'damage')).toBe(true);
        // Fury's accuracy effect is not Fury's damage effect
        expect(isFuryEntry('/buff_uniques/fury_accuracy', '/buff_types/accuracy', 'damage')).toBe(false);
        expect(isFuryEntry('/buff_uniques/precision', '/buff_types/accuracy', 'accuracy')).toBe(false);
        expect(isFuryEntry('/buff_uniques/berserk', '/buff_types/damage', 'damage')).toBe(false);
    });

    it('reads a discriminating reading off the wire shape', () => {
        const unit = buildUnit({ acc: { ...WIDE, model: 'multiplicative' }, dmg: { ...WIDE } });
        expect(readMetric('accuracy', unit).discriminating).toBe(true);
        expect(readMetric('damage', unit).discriminating).toBe(true);
    });
});

describe('a discriminating reading', () => {
    it('picks multiplicative when the game generated it multiplicatively', () => {
        const unit = buildUnit({ acc: { ...WIDE, model: 'multiplicative' }, dmg: { ...WIDE } });
        const reading = readMetric('accuracy', unit);

        expect(reading.discriminating).toBe(true);
        expect(reading.outcome).toBe('multiplicative');
        expect(reading.reason).toBeNull();
        // The predicted gap is base × d × f, comfortably over the bar
        expect(reading.deciding[0].gap).toBeCloseTo(BASE * WIDE.d * WIDE.f, 6);
        expect(reading.deciding[0].gap).toBeGreaterThan(MIN_GAP_UNITS);
        expect(Math.abs(reading.deciding[0].errorMultiplicative)).toBeLessThanOrEqual(1);
        expect(Math.abs(reading.deciding[0].errorAdditive)).toBeGreaterThan(1);
    });

    it('picks additive when the game generated it additively', () => {
        const unit = buildUnit({ acc: { ...WIDE, model: 'additive' }, dmg: { ...WIDE, model: 'additive' } });
        const reading = readMetric('damage', unit);

        expect(reading.discriminating).toBe(true);
        expect(reading.outcome).toBe('additive');
        expect(Math.abs(reading.deciding[0].errorAdditive)).toBeLessThanOrEqual(1);
        expect(Math.abs(reading.deciding[0].errorMultiplicative)).toBeGreaterThan(1);
    });

    it('records every style, magic included, as its own vote', () => {
        const unit = buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE } });
        const reading = readMetric('accuracy', unit);
        const voted = reading.deciding.map((sub) => sub.style);
        expect(voted).toContain('magic');
        expect(voted).toContain('ranged');
        expect(voted).toContain('stab');
        expect(reading.deciding.every((sub) => sub.matched === 'multiplicative')).toBe(true);
    });
});

describe('readings that cannot tell the models apart', () => {
    it('separates a snapshot carrying no buffs at all from one with Fury down', () => {
        // Identical tallies under the old shape, opposite meanings: the first
        // is a reader that is not being fed, the second is a quiet fight
        const blind = readMetric('accuracy', buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE }, noBuffMap: true }));
        expect(blind.discriminating).toBe(false);
        expect(blind.reason).toBe('noBuffMap');

        const quiet = readMetric('accuracy', buildUnit({ acc: { d: 0.8, f: 0 }, dmg: { d: 0.8, f: 0 } }));
        expect(quiet.reason).toBe('noFury');
    });

    it('refuses a reading with no Fury, however well it matches', () => {
        const unit = buildUnit({ acc: { d: 0.8, f: 0 }, dmg: { d: 0.8, f: 0 } });
        const reading = readMetric('accuracy', unit);

        // Both models reproduce the game's number exactly — and that is the trap
        expect(reading.discriminating).toBe(false);
        expect(reading.reason).toBe('noFury');
        expect(reading.outcome).toBeNull();
    });

    it('refuses a reading with Fury but no other buff of that type', () => {
        const unit = buildUnit({ acc: { d: 0, f: 0.6 }, dmg: { d: 0, f: 0.6 } });
        const reading = readMetric('damage', unit);

        expect(reading.discriminating).toBe(false);
        expect(reading.reason).toBe('noOtherBuff');
    });

    it('refuses a reading whose predicted gap rounding could hide', () => {
        const unit = buildUnit({ acc: { d: 0.1, f: 0.1 }, dmg: { d: 0.1, f: 0.1 } });
        const reading = readMetric('accuracy', unit);

        // base × d × f = 1.65, under the bar — a single rounded value could
        // satisfy both models
        expect(BASE * 0.1 * 0.1).toBeLessThan(MIN_GAP_UNITS);
        expect(reading.discriminating).toBe(false);
        expect(reading.reason).toBe('gapTooSmall');
    });

    it('refuses a reading carrying a flat boost neither model has a term for', () => {
        const unit = buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE }, accFlat: 12 });
        expect(readMetric('accuracy', unit).reason).toBe('flatBoost');
        // The damage side carries no flat boost and is graded as usual
        expect(readMetric('damage', unit).discriminating).toBe(true);
    });

    it('refuses a snapshot with no numbers in it', () => {
        expect(readMetric('accuracy', { combatDetails: null }).reason).toBe('noData');
    });
});

describe('a reading neither model explains', () => {
    it('is counted as neither rather than forced onto a side', () => {
        const unit = buildUnit({ acc: { ...WIDE, scale: 1.2 }, dmg: { ...WIDE, scale: 1.2 } });
        const reading = readMetric('accuracy', unit);

        expect(reading.discriminating).toBe(true);
        expect(reading.outcome).toBe('neither');

        const tally = foldReading(emptyTally(), readUnit(unit), 1000);
        expect(tally.accuracy.neither).toBe(1);
        expect(tally.accuracy.multiplicative).toBe(0);
        expect(tally.accuracy.additive).toBe(0);

        const summary = summarize(tally, wilsonInterval);
        expect(summary.metrics.accuracy.verdict.decided).toBe(false);
        expect(summary.metrics.accuracy.verdict.text).toContain('neither');
    });
});

describe('the tally', () => {
    it('counts a repeat of the same numbers once', () => {
        const unit = buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE } });
        const tally = emptyTally();
        foldReading(tally, readUnit(unit), 1000);
        foldReading(tally, readUnit(unit), 2000);

        expect(tally.accuracy.discriminating).toBe(1);
        expect(tally.accuracy.reasons.duplicate).toBe(1);
        expect(tally.accuracy.readings).toBe(2);
    });

    it('keeps the non-discriminating readings visible instead of dropping them', () => {
        const tally = emptyTally();
        foldReading(tally, readUnit(buildUnit({ acc: { d: 0.8, f: 0 }, dmg: { d: 0.8, f: 0 } })), 1000);

        const summary = summarize(tally, wilsonInterval);
        expect(summary.metrics.accuracy.discriminating).toBe(0);
        expect(summary.metrics.accuracy.nonDiscriminating).toBe(1);
        expect(summary.metrics.accuracy.verdict.text).toContain(`0 of ${MIN_READINGS}`);
    });
});

describe('accuracy and damage are graded apart', () => {
    it('reaches a verdict on one while the other has nothing to go on', () => {
        const tally = emptyTally();
        for (let i = 0; i < MIN_READINGS; i += 1) {
            // Vary Fury a little so each reading is genuinely a new observation
            const unit = buildUnit({
                acc: { d: 0.5, f: 0.4 + i * 0.01, model: 'multiplicative' },
                dmg: { d: 0.5, f: 0 },
            });
            foldReading(tally, readUnit(unit), 1000 + i);
        }

        const summary = summarize(tally, wilsonInterval);

        expect(summary.metrics.accuracy.discriminating).toBe(MIN_READINGS);
        expect(summary.metrics.accuracy.multiplicative).toBe(MIN_READINGS);
        expect(summary.metrics.accuracy.verdict.decided).toBe(true);
        expect(summary.metrics.accuracy.verdict.text).toContain('MULTIPLICATIVE');

        expect(summary.metrics.damage.discriminating).toBe(0);
        expect(summary.metrics.damage.verdict.decided).toBe(false);
        expect(summary.metrics.damage.reasons.find((row) => row.reason === 'noFury').count).toBe(MIN_READINGS);
    });

    it('can call damage additive while accuracy is multiplicative', () => {
        const tally = emptyTally();
        for (let i = 0; i < MIN_READINGS; i += 1) {
            const unit = buildUnit({
                acc: { d: 0.5, f: 0.4 + i * 0.01, model: 'multiplicative' },
                dmg: { d: 0.5, f: 0.4 + i * 0.01, model: 'additive' },
            });
            foldReading(tally, readUnit(unit), 1000 + i);
        }

        const summary = summarize(tally, wilsonInterval);
        expect(summary.metrics.accuracy.verdict.text).toContain('MULTIPLICATIVE');
        expect(summary.metrics.damage.verdict.text).toContain('ADDITIVE');
        expect(summary.metrics.damage.additive).toBe(MIN_READINGS);
    });

    it('keeps a per-style breakdown without inflating the reading count', () => {
        const tally = emptyTally();
        const unit = buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE } });
        foldReading(tally, readUnit(unit), 1000);

        const summary = summarize(tally, wilsonInterval);
        expect(summary.metrics.accuracy.discriminating).toBe(1);
        // Five styles voted inside that one reading
        const styles = summary.metrics.accuracy.styles.filter((style) => style.discriminating);
        expect(styles).toHaveLength(5);
        expect(styles.every((style) => style.multiplicative === 1)).toBe(true);
    });

    it('holds a handful of audit rows with both predictions on them', () => {
        const tally = emptyTally();
        foldReading(tally, readUnit(buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE } })), 1000);

        const row = tally.audit.find((entry) => entry.metric === 'accuracy');
        expect(row.outcome).toBe('multiplicative');
        expect(row.game).toBe(Math.round(BASE * factor('multiplicative', WIDE.d, WIDE.f)));
        expect(row.multiplicative).toBeCloseTo(BASE * 1.5 * 1.4, 2);
        expect(row.additive).toBeCloseTo(BASE * 1.9, 2);
        expect(row.gap).toBeCloseTo(BASE * WIDE.d * WIDE.f, 2);
    });
});

describe('a check that is not finding Fury says so', () => {
    /** One snapshot's worth of sighting, as `readUnit` reports it. */
    const sighting = (map) => observeBuffs(map);

    it('counts what the buff map held, Fury included', () => {
        const seen = sighting(buffMap({ acc: { d: 0.5, f: 0.4 }, dmg: { d: 0.5, f: 0.4 } }));
        expect(seen.entries).toBe(4);
        expect(seen.fury).toBe(2);
        expect(seen.uniques).toContain('/buff_uniques/fury_accuracy');
    });

    it('is healthy while Fury is being found', () => {
        const tally = emptyTally();
        foldReading(tally, readUnit(buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE } })), 1000);
        const summary = summarize(tally, wilsonInterval);
        expect(summary.observed.withFury).toBe(1);
        expect(summary.health.ok).toBe(true);
    });

    it('calls a long run with Fury never once seen a fault, not patience', () => {
        // Exactly the live failure: readings pile up, every one lands under
        // noFury, and the panel reads as a patient zero. It is not one.
        const tally = emptyTally();
        for (let i = 0; i < FURY_ALARM_READINGS; i += 1) {
            const unit = buildUnit({ acc: { d: 0.8, f: 0 }, dmg: { d: 0.8, f: 0 } });
            delete unit.combatBuffMap['/buff_uniques/fury_accuracy'];
            delete unit.combatBuffMap['/buff_uniques/fury_damage'];
            foldReading(tally, readUnit(unit), 1000 + i);
        }

        const summary = summarize(tally, wilsonInterval);
        expect(summary.metrics.accuracy.discriminating).toBe(0);
        expect(summary.observed.units).toBe(FURY_ALARM_READINGS);
        expect(summary.observed.withFury).toBe(0);
        expect(summary.health.ok).toBe(false);
        expect(summary.health.text).toContain('NOT FINDING FURY');
        // And it names what it did see, which is what tells a renamed buff
        // from an absent one
        expect(summary.health.text).toContain('precision');
    });

    it('distinguishes a reader that is being fed no buffs at all', () => {
        const tally = emptyTally();
        for (let i = 0; i < FURY_ALARM_READINGS; i += 1) {
            foldReading(tally, readUnit(buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE }, noBuffMap: true })), 1000 + i);
        }

        const summary = summarize(tally, wilsonInterval);
        expect(summary.health.ok).toBe(false);
        expect(summary.health.text).toContain('NOT READING BUFFS');
        expect(summary.metrics.accuracy.reasons.find((row) => row.reason === 'noBuffMap').count).toBe(
            FURY_ALARM_READINGS
        );
    });

    it('holds its tongue while the sample is still short', () => {
        expect(healthOf({ units: 3, withBuffMap: 3, withFury: 0, types: {}, uniques: [] }).ok).toBe(true);
        expect(healthOf({ units: 0, withBuffMap: 0, withFury: 0, types: {}, uniques: [] }).ok).toBe(true);
    });
});
