import { describe, it, expect } from 'vitest';
import { wilsonInterval } from '../combat-sim/engine/wilson.js';
import {
    emptyTally,
    foldReading,
    readMetric,
    readUnit,
    summarize,
    sumBoost,
    MIN_READINGS,
    MIN_GAP_UNITS,
} from './fury-stacking.js';

const LEVEL = 100;
const GEAR = 0.5;
/** (10 + level) × (1 + gear ratio) — the base every style here is built from. */
const BASE = (10 + LEVEL) * (1 + GEAR);

const STYLES = ['stab', 'slash', 'smash', 'ranged', 'magic'];

/**
 * The factor one model puts on the base.
 * @param {string} model - 'multiplicative' or 'additive'
 * @param {number} d - Non-Fury ratio boost
 * @param {number} f - Fury ratio boost
 * @returns {number} The factor
 */
function factor(model, d, f) {
    return model === 'multiplicative' ? (1 + d) * (1 + f) : 1 + d + f;
}

/**
 * A synthetic player snapshot whose resolved numbers were generated by a known
 * model, so the check's verdict is checkable against the truth that made it.
 *
 * `scale` deliberately breaks both models at once, for the reading that should
 * match neither.
 *
 * @param {Object} spec - What to build
 * @param {{d: number, f: number, model?: string, scale?: number}} spec.acc - Accuracy terms
 * @param {{d: number, f: number, model?: string, scale?: number}} spec.dmg - Damage terms
 * @param {number} [spec.accFlat] - A flat boost on the accuracy buff type
 * @returns {Object} A unit with `combatDetails` and `combatBuffMap`
 */
function buildUnit({ acc, dmg, accFlat = 0 }) {
    const accFactor = factor(acc.model || 'multiplicative', acc.d, acc.f) * (acc.scale ?? 1);
    const dmgFactor = factor(dmg.model || 'multiplicative', dmg.d, dmg.f) * (dmg.scale ?? 1);

    const combatStats = { defensiveDamage: 0 };
    const combatDetails = {
        attackLevel: LEVEL,
        meleeLevel: LEVEL,
        rangedLevel: LEVEL,
        magicLevel: LEVEL,
        defenseLevel: LEVEL,
        combatStats,
    };
    for (const style of STYLES) {
        combatStats[`${style}Accuracy`] = GEAR;
        combatStats[`${style}Damage`] = GEAR;
        combatDetails[`${style}AccuracyRating`] = Math.round(BASE * accFactor);
        combatDetails[`${style}MaxDamage`] = Math.round(BASE * dmgFactor);
    }
    combatDetails.defensiveMaxDamage = Math.round((10 + LEVEL) * dmgFactor);

    return {
        isPlayer: true,
        combatDetails,
        combatBuffMap: {
            '/buff_uniques/precision': {
                typeHrid: '/buff_types/accuracy',
                ratioBoost: acc.d,
                flatBoost: accFlat,
            },
            '/buff_uniques/fury_a': { typeHrid: '/buff_types/fury_accuracy', ratioBoost: acc.f, flatBoost: 0 },
            '/buff_uniques/berserk': { typeHrid: '/buff_types/damage', ratioBoost: dmg.d, flatBoost: 0 },
            '/buff_uniques/fury_d': { typeHrid: '/buff_types/fury_damage', ratioBoost: dmg.f, flatBoost: 0 },
        },
    };
}

/** A pair of terms wide enough that the two models cannot both be satisfied. */
const WIDE = { d: 0.5, f: 0.4 };

describe('sumBoost', () => {
    it('totals every buff of a type, the way the engine does', () => {
        const map = {
            a: { typeHrid: '/buff_types/damage', ratioBoost: 0.1, flatBoost: 0 },
            b: { typeHrid: '/buff_types/damage', ratioBoost: 0.2, flatBoost: 3 },
            c: { typeHrid: '/buff_types/accuracy', ratioBoost: 0.9, flatBoost: 0 },
        };
        expect(sumBoost(map, '/buff_types/damage')).toEqual({ ratio: 0.30000000000000004, flat: 3 });
        expect(sumBoost(map, '/buff_types/fury_damage')).toEqual({ ratio: 0, flat: 0 });
    });
});

describe('a discriminating reading', () => {
    it('picks multiplicative when the game generated it multiplicatively', () => {
        const unit = buildUnit({ acc: { ...WIDE, model: 'multiplicative' }, dmg: { ...WIDE } });
        const reading = readMetric('accuracy', unit);

        expect(reading.discriminating).toBe(true);
        expect(reading.outcome).toBe('multiplicative');
        expect(reading.reason).toBeNull();
        // The predicted gap is base × d × f, comfortably over the bar
        expect(reading.deciding[0].gap).toBeCloseTo(BASE * WIDE.d * WIDE.f, 6);
        expect(reading.deciding[0].gap).toBeGreaterThan(MIN_GAP_UNITS);
        expect(Math.abs(reading.deciding[0].errorMultiplicative)).toBeLessThanOrEqual(1);
        expect(Math.abs(reading.deciding[0].errorAdditive)).toBeGreaterThan(1);
    });

    it('picks additive when the game generated it additively', () => {
        const unit = buildUnit({ acc: { ...WIDE, model: 'additive' }, dmg: { ...WIDE, model: 'additive' } });
        const reading = readMetric('damage', unit);

        expect(reading.discriminating).toBe(true);
        expect(reading.outcome).toBe('additive');
        expect(Math.abs(reading.deciding[0].errorAdditive)).toBeLessThanOrEqual(1);
        expect(Math.abs(reading.deciding[0].errorMultiplicative)).toBeGreaterThan(1);
    });

    it('records every style, magic included, as its own vote', () => {
        const unit = buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE } });
        const reading = readMetric('accuracy', unit);
        const voted = reading.deciding.map((sub) => sub.style);
        expect(voted).toContain('magic');
        expect(voted).toContain('ranged');
        expect(voted).toContain('stab');
        expect(reading.deciding.every((sub) => sub.matched === 'multiplicative')).toBe(true);
    });
});

describe('readings that cannot tell the models apart', () => {
    it('refuses a reading with no Fury, however well it matches', () => {
        const unit = buildUnit({ acc: { d: 0.8, f: 0 }, dmg: { d: 0.8, f: 0 } });
        const reading = readMetric('accuracy', unit);

        // Both models reproduce the game's number exactly — and that is the trap
        expect(reading.discriminating).toBe(false);
        expect(reading.reason).toBe('noFury');
        expect(reading.outcome).toBeNull();
    });

    it('refuses a reading with Fury but no other buff of that type', () => {
        const unit = buildUnit({ acc: { d: 0, f: 0.6 }, dmg: { d: 0, f: 0.6 } });
        const reading = readMetric('damage', unit);

        expect(reading.discriminating).toBe(false);
        expect(reading.reason).toBe('noOtherBuff');
    });

    it('refuses a reading whose predicted gap rounding could hide', () => {
        const unit = buildUnit({ acc: { d: 0.1, f: 0.1 }, dmg: { d: 0.1, f: 0.1 } });
        const reading = readMetric('accuracy', unit);

        // base × d × f = 1.65, under the bar — a single rounded value could
        // satisfy both models
        expect(BASE * 0.1 * 0.1).toBeLessThan(MIN_GAP_UNITS);
        expect(reading.discriminating).toBe(false);
        expect(reading.reason).toBe('gapTooSmall');
    });

    it('refuses a reading carrying a flat boost neither model has a term for', () => {
        const unit = buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE }, accFlat: 12 });
        expect(readMetric('accuracy', unit).reason).toBe('flatBoost');
        // The damage side carries no flat boost and is graded as usual
        expect(readMetric('damage', unit).discriminating).toBe(true);
    });

    it('refuses a snapshot with no numbers in it', () => {
        expect(readMetric('accuracy', { combatDetails: null }).reason).toBe('noData');
    });
});

describe('a reading neither model explains', () => {
    it('is counted as neither rather than forced onto a side', () => {
        const unit = buildUnit({ acc: { ...WIDE, scale: 1.2 }, dmg: { ...WIDE, scale: 1.2 } });
        const reading = readMetric('accuracy', unit);

        expect(reading.discriminating).toBe(true);
        expect(reading.outcome).toBe('neither');

        const tally = foldReading(emptyTally(), readUnit(unit), 1000);
        expect(tally.accuracy.neither).toBe(1);
        expect(tally.accuracy.multiplicative).toBe(0);
        expect(tally.accuracy.additive).toBe(0);

        const summary = summarize(tally, wilsonInterval);
        expect(summary.metrics.accuracy.verdict.decided).toBe(false);
        expect(summary.metrics.accuracy.verdict.text).toContain('neither');
    });
});

describe('the tally', () => {
    it('counts a repeat of the same numbers once', () => {
        const unit = buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE } });
        const tally = emptyTally();
        foldReading(tally, readUnit(unit), 1000);
        foldReading(tally, readUnit(unit), 2000);

        expect(tally.accuracy.discriminating).toBe(1);
        expect(tally.accuracy.reasons.duplicate).toBe(1);
        expect(tally.accuracy.readings).toBe(2);
    });

    it('keeps the non-discriminating readings visible instead of dropping them', () => {
        const tally = emptyTally();
        foldReading(tally, readUnit(buildUnit({ acc: { d: 0.8, f: 0 }, dmg: { d: 0.8, f: 0 } })), 1000);

        const summary = summarize(tally, wilsonInterval);
        expect(summary.metrics.accuracy.discriminating).toBe(0);
        expect(summary.metrics.accuracy.nonDiscriminating).toBe(1);
        expect(summary.metrics.accuracy.verdict.text).toContain(`0 of ${MIN_READINGS}`);
    });
});

describe('accuracy and damage are graded apart', () => {
    it('reaches a verdict on one while the other has nothing to go on', () => {
        const tally = emptyTally();
        for (let i = 0; i < MIN_READINGS; i += 1) {
            // Vary Fury a little so each reading is genuinely a new observation
            const unit = buildUnit({
                acc: { d: 0.5, f: 0.4 + i * 0.01, model: 'multiplicative' },
                dmg: { d: 0.5, f: 0 },
            });
            foldReading(tally, readUnit(unit), 1000 + i);
        }

        const summary = summarize(tally, wilsonInterval);

        expect(summary.metrics.accuracy.discriminating).toBe(MIN_READINGS);
        expect(summary.metrics.accuracy.multiplicative).toBe(MIN_READINGS);
        expect(summary.metrics.accuracy.verdict.decided).toBe(true);
        expect(summary.metrics.accuracy.verdict.text).toContain('MULTIPLICATIVE');

        expect(summary.metrics.damage.discriminating).toBe(0);
        expect(summary.metrics.damage.verdict.decided).toBe(false);
        expect(summary.metrics.damage.reasons.find((row) => row.reason === 'noFury').count).toBe(MIN_READINGS);
    });

    it('can call damage additive while accuracy is multiplicative', () => {
        const tally = emptyTally();
        for (let i = 0; i < MIN_READINGS; i += 1) {
            const unit = buildUnit({
                acc: { d: 0.5, f: 0.4 + i * 0.01, model: 'multiplicative' },
                dmg: { d: 0.5, f: 0.4 + i * 0.01, model: 'additive' },
            });
            foldReading(tally, readUnit(unit), 1000 + i);
        }

        const summary = summarize(tally, wilsonInterval);
        expect(summary.metrics.accuracy.verdict.text).toContain('MULTIPLICATIVE');
        expect(summary.metrics.damage.verdict.text).toContain('ADDITIVE');
        expect(summary.metrics.damage.additive).toBe(MIN_READINGS);
    });

    it('keeps a per-style breakdown without inflating the reading count', () => {
        const tally = emptyTally();
        const unit = buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE } });
        foldReading(tally, readUnit(unit), 1000);

        const summary = summarize(tally, wilsonInterval);
        expect(summary.metrics.accuracy.discriminating).toBe(1);
        // Five styles voted inside that one reading
        const styles = summary.metrics.accuracy.styles.filter((style) => style.discriminating);
        expect(styles).toHaveLength(5);
        expect(styles.every((style) => style.multiplicative === 1)).toBe(true);
    });

    it('holds a handful of audit rows with both predictions on them', () => {
        const tally = emptyTally();
        foldReading(tally, readUnit(buildUnit({ acc: { ...WIDE }, dmg: { ...WIDE } })), 1000);

        const row = tally.audit.find((entry) => entry.metric === 'accuracy');
        expect(row.outcome).toBe('multiplicative');
        expect(row.game).toBe(Math.round(BASE * factor('multiplicative', WIDE.d, WIDE.f)));
        expect(row.multiplicative).toBeCloseTo(BASE * 1.5 * 1.4, 2);
        expect(row.additive).toBeCloseTo(BASE * 1.9, 2);
        expect(row.gap).toBeCloseTo(BASE * WIDE.d * WIDE.f, 2);
    });
});
